# This file was generated by GoReleaser. DO NOT EDIT.
cask "terrax" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "f8451ff2acaa9890e5cb9349efb650553d726e0dd12617740494bbb37d288d4d"
      url "https://github.com/israoo/terrax/releases/download/v#{version}/terrax_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a526c8e66217f6e49206b5259ae634d90825c8614e8d448043c614fa44222df9"
      url "https://github.com/israoo/terrax/releases/download/v#{version}/terrax_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "231dffef044cec67786d45ecc9d4055f2325b77583ec9b6fb321ded141bfd9eb"
      url "https://github.com/israoo/terrax/releases/download/v#{version}/terrax_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bfc0e26d3b351601f2d39189a164c296c44e7d49af7b165d431970349ed2a205"
      url "https://github.com/israoo/terrax/releases/download/v#{version}/terrax_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "terrax"
  desc "The interactive TUI executor for Terragrunt stacks"
  homepage "https://github.com/israoo/terrax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terrax"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terrax"]
    end
  end

  # No zap stanza required

end
