# This file was generated by GoReleaser. DO NOT EDIT.
cask "terrax" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "1e85d2c6d5733c4aa20d51066604b42e9ff0fec805e17f1acb1f287a2e70547f"
      url "https://github.com/israoo/terrax/releases/download/v#{version}/terrax_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8fd5109bc85e6ebebb590581b922decd163d34d0f814b3d450856eb9f9ac2c0b"
      url "https://github.com/israoo/terrax/releases/download/v#{version}/terrax_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f4b275c386cfbf12e3da94b903f8a2c6c70c16c9becd40f761108626be26e138"
      url "https://github.com/israoo/terrax/releases/download/v#{version}/terrax_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ac501b60cb1e64a8ed2b47e8c2c16602ac22653dd00a1cff40376f252ccb8e50"
      url "https://github.com/israoo/terrax/releases/download/v#{version}/terrax_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "terrax"
  desc "The interactive TUI executor for Terragrunt stacks"
  homepage "https://github.com/israoo/terrax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terrax"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terrax"]
    end
  end

  # No zap stanza required

end
